// GX policy reference uses Aurora TextureBind::get_descriptor. Hardware words
// are generated by the actual requested SharpProspero sampler implementation.
using SharpProspero.Graphics.Agc;
using var output = new BinaryWriter(File.Create(args[0]));
AgcAddressMode[] wraps = [AgcAddressMode.ClampToEdge, AgcAddressMode.Wrap, AgcAddressMode.Mirror];
bool[] linearMin = [false,false,false,false,true,true,true,false];
AgcMipFilter[] mips = [AgcMipFilter.None,AgcMipFilter.Point,AgcMipFilter.Linear,AgcMipFilter.None,
    AgcMipFilter.None,AgcMipFilter.Point,AgcMipFilter.Linear,AgcMipFilter.None];
uint count = 0;
foreach(uint s in Enumerable.Range(0,3)) foreach(uint t in Enumerable.Range(0,3))
foreach(uint hw in Enumerable.Range(0,8)) foreach(uint mag in Enumerable.Range(0,2))
foreach(uint gxAniso in Enumerable.Range(0,4)) foreach(uint configured in new uint[]{1,2,4,8,16})
foreach(uint arbitrary in Enumerable.Range(0,2)) {
    uint lo=(count*17)%256,hi=lo+((count*31)%(256-lo));
    var mode0=s|(t<<2)|(hw<<5)|(mag<<4)|(gxAniso<<19)|(((count*7)&255)<<9);
    var mode1=lo|(hi<<8);
    var mip=mips[hw]; if(arbitrary!=0 && mip!=AgcMipFilter.None) mip=AgcMipFilter.Linear;
    uint aniso=gxAniso==1?Math.Max(configured/2,1):gxAniso==2?configured:1;
    if(mag==0 || !linearMin[hw] || mip!=AgcMipFilter.Linear) aniso=1;
    var descriptor=AgcSamplerDescriptor.Create();
    descriptor.SetAddressModes(wraps[s],wraps[t],AgcAddressMode.Wrap);
    descriptor.SetFilter(aniso>1?AgcFilter.AnisotropicBilinear:mag!=0?AgcFilter.Bilinear:AgcFilter.Point,
        aniso>1?AgcFilter.AnisotropicBilinear:linearMin[hw]?AgcFilter.Bilinear:AgcFilter.Point,mip);
    descriptor.SetMaxAnisotropy(System.Numerics.BitOperations.Log2(aniso));
    descriptor.SetLodRange(mip==AgcMipFilter.None?0:lo/16f,mip==AgcMipFilter.None?0:hi/16f);
    output.Write(mode0);output.Write(mode1);output.Write(arbitrary);output.Write(configured);
    for(int i=0;i<4;++i) output.Write(descriptor[i]);
    ++count;
}
Console.WriteLine($"Generated {count} GX sampler reference descriptors with SharpProspero");
