// SPDX-License-Identifier: GPL-3.0-only
// Uses the requested SharpProspero source directly for tiling and descriptors.
using SharpProspero.Graphics.Agc;
using System.Text;
using System.Text.Json;
if (args.Length is not (1 or 2 or 3)) throw new ArgumentException("agc_fixture output.h [tev-cases.json [programs.bin]]");
var texture = new AgcSurfaceDescription(AgcTileMode.RenderTarget, AgcSurfaceDimension.TwoD, 64, 64, 4);
var layout = AgcSurface.Compute(texture);
byte[] linear = new byte[64 * 64 * 4], tiled = new byte[checked((int)layout.TotalSizeBytes)];
for (int y = 0; y < 64; ++y) for (int x = 0; x < 64; ++x) {
    int i = (y * 64 + x) * 4;
    linear[i] = (byte)((x < 32 && y < 32) || (x >= 32 && y >= 32) ? 255 : 0);
    linear[i + 1] = (byte)(x >= 32 ? 255 : 0);
    linear[i + 2] = (byte)(y >= 32 ? 255 : 0);
    linear[i + 3] = 255;
}
AgcTiler.Tile(tiled, linear, texture);
byte[] roundtrip = new byte[linear.Length];
AgcTiler.Detile(roundtrip, tiled, texture);
if (!linear.AsSpan().SequenceEqual(roundtrip)) throw new Exception("Texture tiling roundtrip failed");
var t = new AgcTextureDescriptor();
t.SetBaseAddress(0); t.SetDimensions(64, 64); t.SetFormat(56);
t.SetType(AgcImageType.Texture2D); t.SetTilingIndex(27); t.SetMipLevelCount(1);
t.SetChannelOrder(AgcChannelSource.Red, AgcChannelSource.Green, AgcChannelSource.Blue, AgcChannelSource.Alpha);
var s = AgcSamplerDescriptor.Create();
s.SetAddressModes(AgcAddressMode.ClampToEdge, AgcAddressMode.ClampToEdge, AgcAddressMode.ClampToEdge);
s.SetFilter(AgcFilter.Point, AgcFilter.Point, AgcMipFilter.None); s.SetLodRange(0, 0);
var output = new StringBuilder("/* Generated by agc_fixture from SharpProspero. */\n");
output.AppendLine("static const unsigned char fixture_pixels[] = {" + string.Join(',', tiled.Select(b => $"0x{b:x2}")) + "};");
output.AppendLine("static const unsigned int fixture_texture[8] = {" + string.Join(',', Enumerable.Range(0, 8).Select(i => $"0x{t[i]:x8}u")) + "};");
output.AppendLine("static const unsigned int fixture_sampler[4] = {" + string.Join(',', Enumerable.Range(0, 4).Select(i => $"0x{s[i]:x8}u")) + "};");
output.AppendLine("static const unsigned int fixture_pixel_offsets[] = {");
for (uint y=0; y<64; ++y) for (uint x=0; x<64; ++x)
    output.AppendLine($"{AgcTiler.ComputeElementByteOffset(texture, x, y)}u,");
output.AppendLine("};");
var target = new AgcSurfaceDescription(AgcTileMode.RenderTarget, AgcSurfaceDimension.TwoD, 1920, 1080, 4);
output.AppendLine("static const struct { unsigned int offset, expected; } fixture_checks[] = {");
// Quad [-.75,.75] has screen bounds x=240..1680, y=135..945. Interior
// samples avoid filtering/rasterization boundaries and distinguish UV axes.
foreach (uint y in new uint[] { 240, 420, 660, 840 }) foreach (uint x in new uint[] { 420, 780, 1140, 1500 }) {
    bool right = x >= 960, bottom = y >= 540;
    uint expected = !bottom ? (right ? 0xff00ff00u : 0xffff0000u) : (right ? 0xffffffffu : 0xff0000ffu);
    output.AppendLine($"{{{AgcTiler.ComputeElementByteOffset(target, x, y)}u, 0x{expected:x8}u}},");
}
foreach (var (x, y) in new (uint, uint)[] { (64, 64), (1856, 64), (64, 1016), (1856, 1016) })
    output.AppendLine($"{{{AgcTiler.ComputeElementByteOffset(target, x, y)}u, 0xff201828u}},");
output.AppendLine("};");
if (args.Length >= 2) {
    using var cases = JsonDocument.Parse(File.ReadAllText(args[1]));
    if (cases.RootElement.GetArrayLength() != 64 * 32) throw new Exception("Expected 2048 TEV cases");
    byte[]? programs = args.Length == 3 ? File.ReadAllBytes(args[2]) : null;
    if (programs != null && programs.Length != 2048 * 2048) throw new Exception("Invalid TEV program fixture length");
    output.AppendLine($"static const unsigned int fixture_tev_records[][{(programs != null ? 512 : 8)}] = {{");
    int recordIndex = 0;
    foreach (var item in cases.RootElement.EnumerateArray()) {
        var words = programs != null ? Enumerable.Range(0,512).Select(i => System.Buffers.Binary.BinaryPrimitives.ReadUInt32LittleEndian(programs.AsSpan(recordIndex*2048+i*4,4))).ToArray() :
            item.GetProperty("words").EnumerateArray().Select(x => x.GetUInt32()).ToArray();
        if (words.Length != (programs != null ? 512 : 8)) throw new Exception("Invalid TEV record size");
        output.AppendLine("{" + string.Join(',', words.Select(x => $"0x{x:x8}u")) + "},");
        ++recordIndex;
    }
    output.AppendLine("};");
    output.AppendLine("static const struct { unsigned int offset, expected; } fixture_tev_checks[] = {");
    int index = 0;
    foreach (var item in cases.RootElement.EnumerateArray()) {
        // Same quad/UV as texture diagnostic. Read well inside each cell.
        uint x = (uint)(240 + ((index % 64) + 0.5) * 1440 / 64);
        uint y = (uint)(135 + ((index / 64) + 0.5) * 810 / 32);
        uint expected = item.GetProperty("expected").GetUInt32();
        output.AppendLine($"{{{AgcTiler.ComputeElementByteOffset(target, x, y)}u, 0x{expected:x8}u}},");
        ++index;
    }
    foreach (var (x, y) in new (uint, uint)[] { (64, 64), (1856, 64), (64, 1016), (1856, 1016) })
        output.AppendLine($"{{{AgcTiler.ComputeElementByteOffset(target, x, y)}u, 0xff201828u}},");
    output.AppendLine("};");
}
File.WriteAllText(args[0], output.ToString());
Console.WriteLine($"Tiled {layout.TotalSizeBytes} bytes; descriptors and 20 GPU readback sample expectations written.");
