// SPDX-License-Identifier: GPL-3.0-only
// One-second sample window and statistics follow Aurora's present telemetry.
#include "present_history.h"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace mkw::agc {
uint64_t native_present_deadline(uint64_t base,uint64_t interval){
    if(!base||!interval)return 0;
    constexpr uint64_t offset=6500000;
    if(base<interval||base-interval>uint64_t(INT64_MAX)-offset)throw std::invalid_argument("Invalid VI presentation schedule");
    return base-interval+offset;
}
void PresentHistory::record(uint64_t now){
    if(total_&&now<last_)throw std::invalid_argument("Presentation clock moved backwards");
    samples_[write_]={now,total_?now-last_:0};last_=now;++total_;
    write_=(write_+1)%samples_.size();count_=std::min(count_+1,samples_.size());
}
AuroraPresentTiming PresentHistory::snapshot(uint64_t now) const{
    AuroraPresentTiming result{};result.totalPresentCount=total_;
    std::array<double,512> milliseconds{};size_t count=0;
    const auto cutoff=now>1000000000?now-1000000000:0;
    for(size_t i=0;i<count_;++i)if(samples_[i].at>=cutoff&&samples_[i].at<=now&&samples_[i].interval){
        auto ms=double(samples_[i].interval)/1000000;milliseconds[count++]=ms;result.averageFrameTimeMs+=ms;
    }
    result.sampleCount=uint32_t(count);if(!count)return result;
    result.averageFrameTimeMs/=count;result.framesPerSecond=1000/result.averageFrameTimeMs;
    // No duplicate/interpolated slots are generated by this native backend.
    result.effectiveFramesPerSecond=result.framesPerSecond;
    for(size_t i=0;i<count;++i){double d=milliseconds[i]-result.averageFrameTimeMs;result.jitterMs+=d*d;}
    result.jitterMs=std::sqrt(result.jitterMs/count);std::sort(milliseconds.begin(),milliseconds.begin()+count);
    result.p95FrameTimeMs=milliseconds[size_t(std::floor(double(count-1)*.95))];return result;
}
}
