# For the port's freestanding platform objects only. This is not a C++ sysroot.
set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
get_filename_component(MKW_WORKSPACE "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(GLOB MKW_CLANG_CANDIDATES "${MKW_WORKSPACE}/.tools/llvm-mingw-*/bin/clang++.exe")
list(LENGTH MKW_CLANG_CANDIDATES MKW_CLANG_COUNT)
if(NOT MKW_CLANG_COUNT EQUAL 1)
    message(FATAL_ERROR "Expected one local LLVM-MinGW toolchain in .tools")
endif()
list(GET MKW_CLANG_CANDIDATES 0 MKW_CLANG_PATH)
get_filename_component(MKW_LLVM_BIN "${MKW_CLANG_PATH}" DIRECTORY)
set(CMAKE_CXX_COMPILER "${MKW_CLANG_PATH}")
set(CMAKE_ASM_COMPILER "${MKW_LLVM_BIN}/clang.exe")
set(CMAKE_CXX_COMPILER_TARGET x86_64-unknown-freebsd)
set(CMAKE_ASM_COMPILER_TARGET x86_64-unknown-freebsd)
set(CMAKE_AR "${MKW_LLVM_BIN}/llvm-ar.exe")
set(CMAKE_RANLIB "${MKW_LLVM_BIN}/llvm-ranlib.exe")
set(CMAKE_CXX_FLAGS_INIT "--no-default-config -ffreestanding -fno-stack-protector")
set(CMAKE_ASM_FLAGS_INIT "--no-default-config -ffreestanding")
